# Site settings
title: Jonathan Root Design and Development Portfolio
email: jonroot@me.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jonrootdesign
github_username: jaroot32
google_username: jonathanroot15

permalink: /:categories/:title

links:
    - title: about
      url: /about
    - title: work
      url: /work
    - title: articles
      url: /articles
    - title: hire me
      url: /hire-me

# Build settings
markdown: kramdown
