# Site settings
title: Jonathan Root Visual and Web Design Solutions Portfolio
email: jonroot@me.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonathanrootdesign.com" # the base hostname & protocol for your site
github_username: jaroot32
linked_username: jonathanroot

exclude: [node_modules, gulpfile.js]

permalink: /:categories/:title

links:
    - title: About
      url: /About
    - title: Portfolio
      url: /Portfolio
    - title: Approach
      url: /Approach
    - title: Articles
      url: /Articles

# Build settings
markdown: kramdown
