# Site settings
title: Jonathan Root Design and Development Portfolio
email: jonroot@me.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/jonathanRootPortfolio" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jonrootdesign
github_username: jaroot32
google_username: jonathanroot15
custom_js: 
- instafeed.min.js

permalink: /:categories/:title

links:
    - title: about
      url: /about
    - title: portfolio
      url: /portfolio
    - title: articles
      url: /articles

# Build settings
markdown: kramdown
